<template>
  <div class="job-page">
    <!-- HEADER -->
    <div class="job-top">
      <div class="job-title">
        <i class="pi pi-briefcase" />
        <span>Job Page</span>
      </div>

      <div class="job-actions">
        <Button class="btn orbis-primary" outlined type="button">
          <i class="pi pi-folder-open" style="margin-right: 8px" />
          Browse Jobs
        </Button>
        <Button class="btn orbis-primary" type="button">
          <i class="pi pi-search" style="margin-right: 8px" />
          Find Job
        </Button>
      </div>
    </div>

    <!-- STEP 1 -->
    <section class="card section">
      <JobStepHeader
        title="Select a Job Type"
        badge="NEW JOBS"
        subtitle="Choose what you want to create"
      />
      <JobTypeSelector :items="JOB_TYPES" :selected="jobType" @select="selectJobType" />
    </section>

    <!-- STEP 2 -->
    <section v-if="jobType" class="card section">
      <JobStepHeader
        :title="`Mode of Transport for ${jobTypeLabel}`"
        subtitle="Choose the transport mode"
      />
      <ModeSelector :items="MODES" :selected="mode" @select="selectMode" />
    </section>

    <!-- META SECTION -->
    <section v-if="jobType && mode" class="card section">
      <div class="meta-title">{{ `New ${jobTypeLabel} Job — ${modeLabel}` }}</div>

      <div class="grid-3">
        <div class="field">
          <label class="label">Customer Name</label>
          <InputText
            v-model="meta.customerName"
            class="control"
            placeholder="Start typing... (select from CRM)"
          />
        </div>

        <div class="field">
          <label class="label">Account Number</label>
          <InputText v-model="meta.accountNumber" class="control" />
        </div>

        <div class="field">
          <label class="label">Customer Quote Ref</label>
          <InputText
            v-model="meta.customerQuoteRef"
            class="control"
            placeholder="Optional"
          />
        </div>
      </div>

      <div class="grid-3" style="margin-top: 12px">
        <div class="field">
          <label class="label">Job Number</label>
          <!-- ✅ Autogenerated + Readonly -->
          <InputText :modelValue="meta.jobNumber" class="control" readonly />
        </div>

        <div class="field">
          <label class="label">Job Date</label>
          <!-- ✅ PrimeVue Calendar (global) -->
          <Calendar
            v-model="meta.jobDate"
            class="control"
            inputClass="control"
            placeholder="dd/mm/yyyy"
            dateFormat="dd/mm/yy"
            showIcon
            showButtonBar
            :manualInput="false"
          />
        </div>

        <div class="field">
          <label class="label">Mode of Transport</label>
          <InputText :modelValue="modeLabel" class="control" readonly />
        </div>
      </div>
    </section>

    <!-- ✅ FINAL ROW: Docs/Notes LEFT, Actions RIGHT -->
    <div v-if="jobType && mode" class="two-col">
      <!-- LEFT: Documents & Notes -->
      <section class="card section">
        <JobStepHeader
          title="Documents & Notes"
          subtitle="Optional attachments and internal notes"
        />

        <div class="docs-grid">
          <!-- Documents -->
          <div class="drop-box">
            Drag &amp; drop documents
          </div>

          <!-- Notes -->
          <div class="field">
            <label class="label">Internal Notes</label>
            <Textarea
              v-model="internalNotes"
              class="control textarea"
              placeholder="Operational notes, special handling, etc."
              autoResize
            />
          </div>
        </div>
      </section>

      <!-- RIGHT: Create/Cancel actions card -->
      <section class="card section actions">
        <Button class="create-btn orbis-primary" type="button" @click="createJob">
          <i class="pi pi-file" style="margin-right: 8px" />
          Create Job
        </Button>

        <button class="cancel-link" type="button" @click="onCancel">
          <i class="pi pi-times" style="margin-right: 6px" />
          Cancel
        </button>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, watch } from "vue";

import "@/app/pages/jobs/JobPage.css";

import JobStepHeader from "@/app/components/jobs/JobStepHeader.vue";
import JobTypeSelector from "@/app/components/jobs/JobTypeSelector.vue";
import ModeSelector from "@/app/components/jobs/ModeSelector.vue";

import {
  JOB_TYPES,
  MODES,
  jobType,
  mode,
  jobTypeLabel,
  modeLabel,
  selectJobType,
  selectMode,
  resetAll,
  generateJobNumber,
} from "@/app/pages/jobs/JobPage.logic";

const internalNotes = ref("");

const meta = reactive<{
  customerName: string;
  accountNumber: string;
  customerQuoteRef: string;
  jobNumber: string;
  jobDate: Date | null;
}>({
  customerName: "",
  accountNumber: "ACC000000001",
  customerQuoteRef: "",
  jobNumber: "",
  jobDate: null,
});

// ✅ Generate job number once both JobType + Mode are chosen
watch(
  () => [jobType.value, mode.value],
  ([jt, md]) => {
    if (jt && md && !meta.jobNumber) {
      meta.jobNumber = generateJobNumber();
    }
  }
);

function createJob() {
  const payload = {
    job_type: jobType.value,
    mode_of_transport: mode.value,
    customer: meta.customerName,
    account_number: meta.accountNumber,
    quote_ref: meta.customerQuoteRef,
    job_number: meta.jobNumber,
    job_date: meta.jobDate ? formatDate(meta.jobDate) : null,
    note: internalNotes.value,
  };

  console.log("CREATE JOB", payload);
}

// format date to YYYY-MM-DD for backend
function formatDate(d: Date): string {
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

function onCancel() {
  internalNotes.value = "";

  meta.customerName = "";
  meta.accountNumber = "ACC000000001";
  meta.customerQuoteRef = "";
  meta.jobNumber = "";
  meta.jobDate = null;

  resetAll();
}
</script>
