export { default as JobDetailsTabs } from "./JobDetailsTabs.vue"
export { default as RoadJobDetails } from "./road/RoadJobDetails.vue"
export { default as RailJobDetails } from "./rail/RailJobDetails.vue"
export { default as AirJobDetails } from "./air/AirJobDetails.vue"
export { default as SeaJobDetails } from "./sea/SeaJobDetails.vue"
